### ISSUE TITLE
Package requirements

### ISSUE THREAD

**Issue by ck37** [saraemoore/ucbthesisrmd#1]
Hi,

Very cool package, I am giving it a try. One minor item: it might be good to either add a few more packages (pander, tikzDevice, dagR) to the Imports or remove them from the Chapter 1 example markdown, because right now the example doesn't compile without those packages being installed. Not a big deal of course. In my case I wanted to first generate the signature page before editing the chapters.

Cheers,
Chris

**Comment by saraemoore** [comment]
Hi Chris,

Thanks for the feedback. There's a note about this in the README. All packages used in the examples are listed in `Suggests`, as that seemed more appropriate for their use here:

["The ‘Suggests’ field... lists packages that are not necessarily needed. This includes packages used only in examples, tests or vignettes..."](https://cran.r-project.org/doc/manuals/r-release/R-exts.html)

Since those packages aren't imported from in the R code itself, I'm hesitant to add them to `Imports` -- unless you've found a comparable package that does what you've suggested?

**Comment by saraemoore** [comment]
@ck37 -- if you find any rmarkdown template packages which do what you suggest, I'll reopen this issue and make changes accordingly.
